apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image: 482053628475.dkr.ecr.eu-central-1.amazonaws.com/usupport-email-api:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: email-secrets
        - configMapRef:
            name: email-config
        ports:
        - containerPort: 3008
      imagePullSecrets:
      - name: regcred
